name: dictaphone
description: A new dictaphone project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  audioplayers: ^4.0.1
  provider: ^6.0.5
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/recorder.json
    - assets/no-data.json
